export default actions = {
    SET_DEVICES: "SET_DEVICES",
    SET_SCANNING: "SET_SCANNING",
    SCANNER_STARTED: "SCANNER_STARTED",
    UNSUBSCRIBE: "UNSUBSCRIBE",
    DISCOVERED_DEVICE: "DISCOVERED_DEVICE",
    SET_INACTIVE_DEVICES: "SET_INACTIVE_DEVICES"
};
